### ISSUE TITLE
recordTime value too long

### ISSUE THREAD

**Issue by RalphTro** [openepcis/epcis-testdata-generator#34] opened 2023-08-10 13:41 UTC
Dear @Aravinda93 ,
When generating test data via https://test-data-generator.openepcis.io/ui/GenerateEvents, the recordTime value currently has a length which doesn't validate against the JSON schema anymore,
e.g. " recordTime": "2023-08-10T13:22:09.078499373Z",
(BTW: The design template does not require/specify this level of precision.) 
Now, if I paste the generated events into https://www.jsonschemavalidator.net/ and test it against the EPCIS JSON schema, it only validates if I remove at least 2 digits in the ms string. 
Please asjust (I think in most cases, a 1-2 digit ms precision, if at all, is absolutely sufficient anyway.)
Kind regards,
Ralph

**Comment by Aravinda93** [comment] 2023-08-10 13:44
Dear @RalphTro

Thanks a lot for bringing this to the notice, I am on it. I will check and fix it right away.

**Comment by sboeckelmann** [comment] 2023-08-10 14:13
@Aravinda93  This may already have been resolved in current model code-base

**Comment by Aravinda93** [comment] 2023-08-10 14:32
@sboeckelmann Thanks a lot for reminding :) Yes, this has been fixed and I am unable to reproduce it locally.

@RalphTro This issue will be fixed during the next deployment, along with other issues.

Best regards,
Aravinda

**Closed** 2023-08-23 18:44 UTC
Labels: bug, duplicate, wontfix

**Comment by RalphTro** [comment] 2023-08-25 06:32
Many thanks, @Aravinda93  and @sboeckelmann!
